"""
Each new term in the Fibonacci sequence is generated by adding the previous two
 terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""

def main(high):
    # Simple version
    total = 2
    minus_one = 2
    minus_two = 1
    fib_val = 0
    while total < high:
        fib_val = minus_one + minus_two

        if fib_val % 2 == 0:
            total += fib_val

        minus_two = minus_one
        minus_one = fib_val

    return total

def better_main(high):
    # Uses the improved even generating Fibonacci series
    # from the solution pdf on project euler
    total = 10
    minus_one = 8
    minus_two = 2
    fib_val = 0
    while total < high:
        print fib_val
        fib_val = 4 * minus_one + minus_two
        total += fib_val
        minus_two = minus_one
        minus_one = fib_val

    return total

target = 4000000
print(main(target))
print(better_main(target))
